resources:
- name: spring-music
  type: git
  source:
    uri: https://github.com/iferunsewe/spring-music.git
    branch: master
- name: spring-music-cf-resource
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf_resource_username))
    password: ((cf_resource_password))
    organization: engineerbetter
    space: development

jobs:
- name: build-cf
  plan:
  - get: spring-music
    trigger: true
  - task: gradle-build
    config:
      platform: linux
      inputs: 
      - name: spring-music
      outputs:
      - name: compiled-spring-music
      run:
        path: /bin/bash
        args:
        - -euxc
        - |
          ls -la
          cd spring-music
          ./gradlew clean assemble
        user: root
      image_resource:
        type: docker-image
        source:
          repository: gradle
  - put: spring-music-cf-resource
    params:
      manifest: spring-music/manifest.yml
      path: compiled-spring-music
  # get from the git resource
  # put in the cf resource


  #api:https://api.run.pivotal.io
  #space: development
  #organization: engineerbetter


# Every time there is a push on the git repo there will be a get and a puts to the cf resource
